### ISSUE TITLE
Not working with Django 1.10

### ISSUE THREAD

**Issue by nikaro** [divio/django-filer#899]
Hello,

I know that Django 1.10 just poped out, but i wanted to see if it was already working. It seems it's not :smile: 

I installed django-filer, configured a simple app which make use of it, and updated django to 1.10 after that. Here is the trace :

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ff993492ea0>
Traceback (most recent call last):
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/filer/models/__init__.py", line 3, in <module>
    from .clipboardmodels import *  # flake8: noqa
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/filer/models/clipboardmodels.py", line 9, in <module>
    from . import filemodels
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/filer/models/filemodels.py", line 18, in <module>
    from .foldermodels import Folder
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/filer/models/foldermodels.py", line 240, in <module>
    mptt.register(Folder)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/mptt/__init__.py", line 12, in register
    from mptt.models import MPTTModelBase
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/mptt/models.py", line 385, in <module>
    class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/mptt/models.py", line 263, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/mptt/managers.py", line 82, in contribute_to_class
    super(TreeManager, self).contribute_to_class(model, name)
  File "/home/nicolas/.virtualenvs/tmp/lib/python3.5/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
```

I'm not yet experienced to Python/Django to find what is the problem and fix, so i leave it to the experts hoping it will be fixed soon.

Good luck! :+1:

**Comment by wiesson** [comment]
The issue seems related to https://github.com/django-mptt/django-mptt/issues/469#issuecomment-232152830

- Require that _default_manager always is a TreeManager instance.
- Do not touch _base_manager at all.

**Comment by shamanis** [comment]
Django: 1.10, Python: 3.4.2, Mptt: **0.8.6**

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7a05feb9d8>
Traceback (most recent call last):
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/filer/models/__init__.py", line 3, in <module>
    from .clipboardmodels import *  # flake8: noqa
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/filer/models/clipboardmodels.py", line 9, in <module>
    from . import filemodels
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/filer/models/filemodels.py", line 43, in <module>
    class File(PolymorphicModel, mixins.IconsMixin):
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/polymorphic/base.py", line 74, in __new__
    inherited_managers = new_class.get_inherited_managers(attrs)
  File "/home/shaman/Work/envs/ufanet_ru/lib/python3.4/site-packages/polymorphic/base.py", line 148, in get_inherited_managers
    if manager._inherited:
AttributeError: 'Manager' object has no attribute '_inherited'
```

**Comment by glenharris** [comment]
I think that I ran into the same problems.  I am a python/django newbie, so I have no confidence in my solution, but I will put some notes here to help other people...

1) The core problem appears to be with the relationship between django-polymorphic and django 1.10
2)  I ended up using django-polymorphic 1.0b1, and django 1.10.1.
3) That fixed most of the problems, however it was still complaining about the django-filer Image _default_manager not being a PolymorphicManager.  From reading related speculation, it seems as though the problem occurs because BaseImage is an abstract model that derives from File which is a concrete polymorphic model (with polymorphic manager).  In other words, a problem with concrete-abstract-concrete model inheritance in the presence of polymorphism.  I suspect that the correct solution is for django-filer to rejig their model hierarchy, but I have no idea what the right answer is.

The solution that got me up and running (and I am not suggesting anyone else do this - it probably has some nasty polymorphic side-effects) is that I forked django-filer and then in the BaseImage model I added the member 'objects = FileManaqer()' (i.e. same as the manager defined in File).  It felt dirty, but that got me up and running (this is just a play project where I wanted to play with django-filer).

Hope this helps someone.

**Comment by shamanis** [comment]
Latest version 1.2.5 still does not work with Django 1.10. Аn error message is not changed.

**Comment by agusmakmun** [comment]
realy?? :open_mouth:
My gratitude does not use it for my project under Django 1.10

**Comment by jschneier** [comment]
This is now fixed in master.

**Comment by yakky** [comment]
Fixed by #918
Thanks @jschneier for contributing this
